version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Starting install - $(date)"

      - echo "Installing AWS SAM CLI"
      - pip install aws-sam-cli

      - echo "Installing CloudFormation template linting tool cfn-lint"
      - pip install cfn-lint

      - echo "Completed install - $(date)"
  pre_build:
    commands:
      - echo "Starting pre_build - $(date)"

      - echo "Linting CloudFormation template"

      - echo "Completed pre_build - $(date)"
  build:
    commands:
      - echo "Starting build - $(date)"

      - echo "Completed build - $(date)"
artifacts:
  files:
    - ${TEMPLATE_PATH}
    - ${PARAMETER_FILE_NAME}
  discard-paths: no
